language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
install: "pip install -r requirements.txt"
before_script:
   flake8 .
script: nosetests
deploy:
  provider: pypi
  user: vinicius.ronconi
  password:
    secure: Bh3MI6UioW2bmrqOh8FJxyF+wStD2ShzXtobYrkzaxHSnhEKTyr6hT5G94CsSJDLOu3D7ONwNZ4ReEZ/q8EV9DMRGnw5gslKH1q1gU+Drw4+PPw0fihXDmkTxNqJ7ALwuziJNzGOtt2p+y3OyHPZR5Ybcy+gskw3dVzAgwNhGLdGTzlLTpHZBdzT1BfK8YRLlrsnlRJ+0Y+qCmVW067EwDOPbIq6zI8oLLiKXHZhx0FeHjc0UPc7Zxcj2QFAVQz2qii7QYN9OKpWJe2oLdh8WRz211vCGBK3QGoXRu8WJ1a1oriAb8A2oE8cJ8mTdlvFIkaEKp1FVTQVQswwA8xsXCpCEkjooJoDbxGoH/5V6kzMMWDQ0A7AtFw7zDW1bMpcCTxvrS4lAo9nOjpMLORnuL2KC3OWyYRFVr0N8H2YG/M1Rg5T1HgoceXNJ6TdLz31SzN39wGGxtdM2Uye01/49pzwGfXtk8XrT6eyzsHDbi40vRA/bTEVJVAsdrfUT15z3KvK5gRwNR/Dq7u+H5rh3HymypWtPoy5ZmIv4tJFmVvuRa5NOIxrNYMgsw8zUVI6w6IzOP3tg2C50/eKJ+j47VKhSsOxuHKdWSE0wnBNalJB4f9xLxaPQoQPGRjuk5WR5cQgBXt6E8zKIBpSD2Y6+bdkquIfr3JqjKbeWsFtx1o=
  on:
    tags: true
    branch: master
