language: python
python:
- '3.4'
- '3.5'
- 3.5-dev
- nightly
install: pip install -r requirements.txt
before_script: flake8 .
script: nosetests
deploy:
  provider: pypi
  user: vinicius.ronconi
  password:
    secure: QnO33LD/Qqy9rJijJszXuVlV6nMeHiHsi2Ii9fuEPOmHMyEGONJWmXpcBGkI0Om8tIek4XiBen/tlaVIYnyea7JWNnsp38DTh3XgE/1fA3HUVJCvw2aqtOTsdkEzBp8+oCiMKx9OQvFVFO8ywlPROPUqa744sqbJNh2U5XQZe+r3LXvqYQ+lhX/DDyiPmyNWaaYmKua1ri8e21M/NWistUZ2KEqsF/4xXDvd2PmvlTI/mgqO5uCF2zTiBVnsOIqC9Y2T6BPtMQYPJ4nUiA0kNH/NhlhYICEp8WBV7jf3pgbEBlJCLPgiX+WdsLjxTLzkxa14oJtOa0pZRMvjaBPBWriDZDPTrbpENk2vUWyMs+0l1HHmtXnmpWFeXCUtMOex24vdrtqKJsuXRR/StD6cnPD4W736sxunT5ZiKDkdj5lZf0RHKajmSJW+bFQummbNIU9Z+3vrUEFGNB8pC/0NQu6VcgaaMUTJLbLfMn84haGm3yXymK2hb4ybSqZHBxrieG/E3D1lbVI7s37UVPaROPOoZv6ZARqkDGRGvOo2LbbEel+EsElirBzx6VCDO8zZLb/ZYLGSWaiQsqGCo/LFGlAg7EXSv3vz9Ems2sG7y5T4GM7e+9eVIC/KnL8UBlmPyIzfMeRKYW5PW/E/jDiY3Wr6JOdhT5rutt6HhiIsF98=
  on:
    distributions: sdist bdist_wheel
    repo: vinicius-ronconi/blinktrade
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = "3.5"
